theme = "tokyonight" 

[editor]
line-number = "absolute"       
mouse = true                   
middle-click-paste = false 
scroll-lines = 3              
shell = ["zsh", "-c"]
auto-save = true               
idle-timeout = 250
completion-trigger-len = 2
auto-completion = true
auto-format = true
auto-pairs = true
color-modes = true
cursorline = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"] # Changed language-id to file-type
separator = "│"

[keys.normal]
S-f = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
S-g = ":sh tmux display-popup -d \"#{pane_current_path}\" -w 90% -h 90% -E lazygit"
C-s = ":write"
C-q = ":quit"
C-o = "file_picker"
C-w = ":buffer-close"
C-d = ":theme tokyonight"
C-l = ":theme bogster_light"
C-h = ":theme heisenberg"
C-k = ":theme kanagawa_trans"
S-y = ":sh zellij run -fc -- yazi"

"C-n" = "goto_previous_buffer"
"C-m" = "goto_next_buffer"

"X" = "extend_line_above"
"G" = "goto_file_end"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"
