
[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt", args = ["--emit=stdout", "--edition=2021"] }


[[language]]
name = "python"
language-servers = [ "ty", "ruff" ]
auto-format = true
roots = ["pyproject.toml", "setup.py", "poetry.lock", "requirements.txt", ".git"]

[language-server.ty]
command = "ty"
args = ["server"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "c"
language-servers = ["clangd"]
formatter = { command = "clang-format", args = ["--style=file"] }
auto-format = true

[[language]]
name = "cpp"
language-servers = ["clangd"]
formatter = { command = "clang-format", args = ["--style=file"] }
auto-format = true

[language-server.clangd]
command = "clangd"
args = ["--background-index", "--clang-tidy", "--completion-style=detailed"]


[[language]]
name = "nim"
scope = "source.nim"
auto-format = true
injection-regex = "nim"
file-types = ["nim", "nims", "nimble"]
roots = ["*.nimble", ".git"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-servers = [ "nimlsp" ]

[language-server.nimlsp]
command = "nimlsp"
